t_encoder_0 = {
    "ht_demucs/encoder_1/conv1d_4/kernel": "tencoder.0.conv.weight",
    "ht_demucs/encoder_1/conv1d_4/bias": "tencoder.0.conv.bias",
    "ht_demucs/encoder_1/conv1d_5/kernel": "tencoder.0.rewrite.weight",
    "ht_demucs/encoder_1/conv1d_5/bias": "tencoder.0.rewrite.bias",
    "ht_demucs/encoder_1/d_conv_1/sequential_2/conv1d_6/kernel": "tencoder.0.dconv.layers.0.0.weight",
    "ht_demucs/encoder_1/d_conv_1/sequential_2/conv1d_6/bias": "tencoder.0.dconv.layers.0.0.bias",
    "ht_demucs/encoder_1/d_conv_1/sequential_2/group_normalization_4/gamma": "tencoder.0.dconv.layers.0.1.weight",
    "ht_demucs/encoder_1/d_conv_1/sequential_2/group_normalization_4/beta": "tencoder.0.dconv.layers.0.1.bias",
    "ht_demucs/encoder_1/d_conv_1/sequential_2/conv1d_7/kernel": "tencoder.0.dconv.layers.0.3.weight",
    "ht_demucs/encoder_1/d_conv_1/sequential_2/conv1d_7/bias": "tencoder.0.dconv.layers.0.3.bias",
    "ht_demucs/encoder_1/d_conv_1/sequential_2/group_normalization_5/gamma": "tencoder.0.dconv.layers.0.4.weight",
    "ht_demucs/encoder_1/d_conv_1/sequential_2/group_normalization_5/beta": "tencoder.0.dconv.layers.0.4.bias",
    "layer_scale_2/scale": "tencoder.0.dconv.layers.0.6.scale",
    "ht_demucs/encoder_1/d_conv_1/sequential_3/conv1d_8/kernel": "tencoder.0.dconv.layers.1.0.weight",
    "ht_demucs/encoder_1/d_conv_1/sequential_3/conv1d_8/bias": "tencoder.0.dconv.layers.1.0.bias",
    "ht_demucs/encoder_1/d_conv_1/sequential_3/group_normalization_6/gamma": "tencoder.0.dconv.layers.1.1.weight",
    "ht_demucs/encoder_1/d_conv_1/sequential_3/group_normalization_6/beta": "tencoder.0.dconv.layers.1.1.bias",
    "ht_demucs/encoder_1/d_conv_1/sequential_3/conv1d_9/kernel": "tencoder.0.dconv.layers.1.3.weight",
    "ht_demucs/encoder_1/d_conv_1/sequential_3/conv1d_9/bias": "tencoder.0.dconv.layers.1.3.bias",
    "ht_demucs/encoder_1/d_conv_1/sequential_3/group_normalization_7/gamma": "tencoder.0.dconv.layers.1.4.weight",
    "ht_demucs/encoder_1/d_conv_1/sequential_3/group_normalization_7/beta": "tencoder.0.dconv.layers.1.4.bias",
    "layer_scale_3/scale": "tencoder.0.dconv.layers.1.6.scale",
}

t_encoder_1 = {
    "ht_demucs/encoder_3/conv1d_15/kernel": "tencoder.1.conv.weight",
    "ht_demucs/encoder_3/conv1d_15/bias": "tencoder.1.conv.bias",
    "ht_demucs/encoder_3/conv1d_16/kernel": "tencoder.1.rewrite.weight",
    "ht_demucs/encoder_3/conv1d_16/bias": "tencoder.1.rewrite.bias",
    "ht_demucs/encoder_3/d_conv_3/sequential_6/conv1d_17/kernel": "tencoder.1.dconv.layers.0.0.weight",
    "ht_demucs/encoder_3/d_conv_3/sequential_6/conv1d_17/bias": "tencoder.1.dconv.layers.0.0.bias",
    "ht_demucs/encoder_3/d_conv_3/sequential_6/group_normalization_12/gamma": "tencoder.1.dconv.layers.0.1.weight",
    "ht_demucs/encoder_3/d_conv_3/sequential_6/group_normalization_12/beta": "tencoder.1.dconv.layers.0.1.bias",
    "ht_demucs/encoder_3/d_conv_3/sequential_6/conv1d_18/kernel": "tencoder.1.dconv.layers.0.3.weight",
    "ht_demucs/encoder_3/d_conv_3/sequential_6/conv1d_18/bias": "tencoder.1.dconv.layers.0.3.bias",
    "ht_demucs/encoder_3/d_conv_3/sequential_6/group_normalization_13/gamma": "tencoder.1.dconv.layers.0.4.weight",
    "ht_demucs/encoder_3/d_conv_3/sequential_6/group_normalization_13/beta": "tencoder.1.dconv.layers.0.4.bias",
    "layer_scale_6/scale": "tencoder.1.dconv.layers.0.6.scale",
    "ht_demucs/encoder_3/d_conv_3/sequential_7/conv1d_19/kernel": "tencoder.1.dconv.layers.1.0.weight",
    "ht_demucs/encoder_3/d_conv_3/sequential_7/conv1d_19/bias": "tencoder.1.dconv.layers.1.0.bias",
    "ht_demucs/encoder_3/d_conv_3/sequential_7/group_normalization_14/gamma": "tencoder.1.dconv.layers.1.1.weight",
    "ht_demucs/encoder_3/d_conv_3/sequential_7/group_normalization_14/beta": "tencoder.1.dconv.layers.1.1.bias",
    "ht_demucs/encoder_3/d_conv_3/sequential_7/conv1d_20/kernel": "tencoder.1.dconv.layers.1.3.weight",
    "ht_demucs/encoder_3/d_conv_3/sequential_7/conv1d_20/bias": "tencoder.1.dconv.layers.1.3.bias",
    "ht_demucs/encoder_3/d_conv_3/sequential_7/group_normalization_15/gamma": "tencoder.1.dconv.layers.1.4.weight",
    "ht_demucs/encoder_3/d_conv_3/sequential_7/group_normalization_15/beta": "tencoder.1.dconv.layers.1.4.bias",
    "layer_scale_7/scale": "tencoder.1.dconv.layers.1.6.scale",
}

t_encoder_2 = {
    "ht_demucs/encoder_5/conv1d_26/kernel": "tencoder.2.conv.weight",
    "ht_demucs/encoder_5/conv1d_26/bias": "tencoder.2.conv.bias",
    "ht_demucs/encoder_5/conv1d_27/kernel": "tencoder.2.rewrite.weight",
    "ht_demucs/encoder_5/conv1d_27/bias": "tencoder.2.rewrite.bias",
    "ht_demucs/encoder_5/d_conv_5/sequential_10/conv1d_28/kernel": "tencoder.2.dconv.layers.0.0.weight",
    "ht_demucs/encoder_5/d_conv_5/sequential_10/conv1d_28/bias": "tencoder.2.dconv.layers.0.0.bias",
    "ht_demucs/encoder_5/d_conv_5/sequential_10/group_normalization_20/gamma": "tencoder.2.dconv.layers.0.1.weight",
    "ht_demucs/encoder_5/d_conv_5/sequential_10/group_normalization_20/beta": "tencoder.2.dconv.layers.0.1.bias",
    "ht_demucs/encoder_5/d_conv_5/sequential_10/conv1d_29/kernel": "tencoder.2.dconv.layers.0.3.weight",
    "ht_demucs/encoder_5/d_conv_5/sequential_10/conv1d_29/bias": "tencoder.2.dconv.layers.0.3.bias",
    "ht_demucs/encoder_5/d_conv_5/sequential_10/group_normalization_21/gamma": "tencoder.2.dconv.layers.0.4.weight",
    "ht_demucs/encoder_5/d_conv_5/sequential_10/group_normalization_21/beta": "tencoder.2.dconv.layers.0.4.bias",
    "layer_scale_10/scale": "tencoder.2.dconv.layers.0.6.scale",
    "ht_demucs/encoder_5/d_conv_5/sequential_11/conv1d_30/kernel": "tencoder.2.dconv.layers.1.0.weight",
    "ht_demucs/encoder_5/d_conv_5/sequential_11/conv1d_30/bias": "tencoder.2.dconv.layers.1.0.bias",
    "ht_demucs/encoder_5/d_conv_5/sequential_11/group_normalization_22/gamma": "tencoder.2.dconv.layers.1.1.weight",
    "ht_demucs/encoder_5/d_conv_5/sequential_11/group_normalization_22/beta": "tencoder.2.dconv.layers.1.1.bias",
    "ht_demucs/encoder_5/d_conv_5/sequential_11/conv1d_31/kernel": "tencoder.2.dconv.layers.1.3.weight",
    "ht_demucs/encoder_5/d_conv_5/sequential_11/conv1d_31/bias": "tencoder.2.dconv.layers.1.3.bias",
    "ht_demucs/encoder_5/d_conv_5/sequential_11/group_normalization_23/gamma": "tencoder.2.dconv.layers.1.4.weight",
    "ht_demucs/encoder_5/d_conv_5/sequential_11/group_normalization_23/beta": "tencoder.2.dconv.layers.1.4.bias",
    "layer_scale_11/scale": "tencoder.2.dconv.layers.1.6.scale",
}

t_encoder_3 = {
    "ht_demucs/encoder_7/conv1d_37/kernel": "tencoder.3.conv.weight",
    "ht_demucs/encoder_7/conv1d_37/bias": "tencoder.3.conv.bias",
    "ht_demucs/encoder_7/conv1d_38/kernel": "tencoder.3.rewrite.weight",
    "ht_demucs/encoder_7/conv1d_38/bias": "tencoder.3.rewrite.bias",
    "ht_demucs/encoder_7/d_conv_7/sequential_14/conv1d_39/kernel": "tencoder.3.dconv.layers.0.0.weight",
    "ht_demucs/encoder_7/d_conv_7/sequential_14/conv1d_39/bias": "tencoder.3.dconv.layers.0.0.bias",
    "ht_demucs/encoder_7/d_conv_7/sequential_14/group_normalization_28/gamma": "tencoder.3.dconv.layers.0.1.weight",
    "ht_demucs/encoder_7/d_conv_7/sequential_14/group_normalization_28/beta": "tencoder.3.dconv.layers.0.1.bias",
    "ht_demucs/encoder_7/d_conv_7/sequential_14/conv1d_40/kernel": "tencoder.3.dconv.layers.0.3.weight",
    "ht_demucs/encoder_7/d_conv_7/sequential_14/conv1d_40/bias": "tencoder.3.dconv.layers.0.3.bias",
    "ht_demucs/encoder_7/d_conv_7/sequential_14/group_normalization_29/gamma": "tencoder.3.dconv.layers.0.4.weight",
    "ht_demucs/encoder_7/d_conv_7/sequential_14/group_normalization_29/beta": "tencoder.3.dconv.layers.0.4.bias",
    "layer_scale_14/scale": "tencoder.3.dconv.layers.0.6.scale",
    "ht_demucs/encoder_7/d_conv_7/sequential_15/conv1d_41/kernel": "tencoder.3.dconv.layers.1.0.weight",
    "ht_demucs/encoder_7/d_conv_7/sequential_15/conv1d_41/bias": "tencoder.3.dconv.layers.1.0.bias",
    "ht_demucs/encoder_7/d_conv_7/sequential_15/group_normalization_30/gamma": "tencoder.3.dconv.layers.1.1.weight",
    "ht_demucs/encoder_7/d_conv_7/sequential_15/group_normalization_30/beta": "tencoder.3.dconv.layers.1.1.bias",
    "ht_demucs/encoder_7/d_conv_7/sequential_15/conv1d_42/kernel": "tencoder.3.dconv.layers.1.3.weight",
    "ht_demucs/encoder_7/d_conv_7/sequential_15/conv1d_42/bias": "tencoder.3.dconv.layers.1.3.bias",
    "ht_demucs/encoder_7/d_conv_7/sequential_15/group_normalization_31/gamma": "tencoder.3.dconv.layers.1.4.weight",
    "ht_demucs/encoder_7/d_conv_7/sequential_15/group_normalization_31/beta": "tencoder.3.dconv.layers.1.4.bias",
    "layer_scale_15/scale": "tencoder.3.dconv.layers.1.6.scale",
}

t_decoder_0 = {
    # Decoder 7 mappings
    "ht_demucs/decoder_7/conv1d_transpose_3/kernel": "tdecoder.0.conv_tr.weight",
    "ht_demucs/decoder_7/conv1d_transpose_3/bias": "tdecoder.0.conv_tr.bias",
    "ht_demucs/decoder_7/conv1d_43/kernel": "tdecoder.0.rewrite.weight",
    "ht_demucs/decoder_7/conv1d_43/bias": "tdecoder.0.rewrite.bias",
}

t_decoder_1 = {
    "ht_demucs/decoder_5/conv1d_transpose_2/kernel": "tdecoder.1.conv_tr.weight",
    "ht_demucs/decoder_5/conv1d_transpose_2/bias": "tdecoder.1.conv_tr.bias",
    "ht_demucs/decoder_5/conv1d_32/kernel": "tdecoder.1.rewrite.weight",
    "ht_demucs/decoder_5/conv1d_32/bias": "tdecoder.1.rewrite.bias",
}

t_decoder_2 = {
    "ht_demucs/decoder_3/conv1d_transpose_1/kernel": "tdecoder.2.conv_tr.weight",
    "ht_demucs/decoder_3/conv1d_transpose_1/bias": "tdecoder.2.conv_tr.bias",
    "ht_demucs/decoder_3/conv1d_21/kernel": "tdecoder.2.rewrite.weight",
    "ht_demucs/decoder_3/conv1d_21/bias": "tdecoder.2.rewrite.bias",
}

t_decoder_3 = {
    "ht_demucs/decoder_1/conv1d_transpose/kernel": "tdecoder.3.conv_tr.weight",
    "ht_demucs/decoder_1/conv1d_transpose/bias": "tdecoder.3.conv_tr.bias",
    "ht_demucs/decoder_1/conv1d_10/kernel": "tdecoder.3.rewrite.weight",
    "ht_demucs/decoder_1/conv1d_10/bias": "tdecoder.3.rewrite.bias",
}

z_encoder_0 = {
    "ht_demucs/encoder/conv2d/kernel": "encoder.0.conv.weight",
    "ht_demucs/encoder/conv2d/bias": "encoder.0.conv.bias",
    "ht_demucs/encoder/conv2d_1/kernel": "encoder.0.rewrite.weight",
    "ht_demucs/encoder/conv2d_1/bias": "encoder.0.rewrite.bias",
    "ht_demucs/encoder/d_conv/sequential/conv1d/kernel": "encoder.0.dconv.layers.0.0.weight",
    "ht_demucs/encoder/d_conv/sequential/conv1d/bias": "encoder.0.dconv.layers.0.0.bias",
    "ht_demucs/encoder/d_conv/sequential/group_normalization/gamma": "encoder.0.dconv.layers.0.1.weight",
    "ht_demucs/encoder/d_conv/sequential/group_normalization/beta": "encoder.0.dconv.layers.0.1.bias",
    "ht_demucs/encoder/d_conv/sequential/conv1d_1/kernel": "encoder.0.dconv.layers.0.3.weight",
    "ht_demucs/encoder/d_conv/sequential/conv1d_1/bias": "encoder.0.dconv.layers.0.3.bias",
    "ht_demucs/encoder/d_conv/sequential/group_normalization_1/gamma": "encoder.0.dconv.layers.0.4.weight",
    "ht_demucs/encoder/d_conv/sequential/group_normalization_1/beta": "encoder.0.dconv.layers.0.4.bias",
    "layer_scale/scale": "encoder.0.dconv.layers.0.6.scale",
    "ht_demucs/encoder/d_conv/sequential_1/conv1d_2/kernel": "encoder.0.dconv.layers.1.0.weight",
    "ht_demucs/encoder/d_conv/sequential_1/conv1d_2/bias": "encoder.0.dconv.layers.1.0.bias",
    "ht_demucs/encoder/d_conv/sequential_1/group_normalization_2/gamma": "encoder.0.dconv.layers.1.1.weight",
    "ht_demucs/encoder/d_conv/sequential_1/group_normalization_2/beta": "encoder.0.dconv.layers.1.1.bias",
    "ht_demucs/encoder/d_conv/sequential_1/conv1d_3/kernel": "encoder.0.dconv.layers.1.3.weight",
    "ht_demucs/encoder/d_conv/sequential_1/conv1d_3/bias": "encoder.0.dconv.layers.1.3.bias",
    "ht_demucs/encoder/d_conv/sequential_1/group_normalization_3/gamma": "encoder.0.dconv.layers.1.4.weight",
    "ht_demucs/encoder/d_conv/sequential_1/group_normalization_3/beta": "encoder.0.dconv.layers.1.4.bias",
    "layer_scale_1/scale": "encoder.0.dconv.layers.1.6.scale",
}

z_encoder_1 = {
    "ht_demucs/encoder_2/conv2d_3/kernel": "encoder.1.conv.weight",
    "ht_demucs/encoder_2/conv2d_3/bias": "encoder.1.conv.bias",
    "ht_demucs/encoder_2/conv2d_4/kernel": "encoder.1.rewrite.weight",
    "ht_demucs/encoder_2/conv2d_4/bias": "encoder.1.rewrite.bias",
    "ht_demucs/encoder_2/d_conv_2/sequential_4/conv1d_11/kernel": "encoder.1.dconv.layers.0.0.weight",
    "ht_demucs/encoder_2/d_conv_2/sequential_4/conv1d_11/bias": "encoder.1.dconv.layers.0.0.bias",
    "ht_demucs/encoder_2/d_conv_2/sequential_4/group_normalization_8/gamma": "encoder.1.dconv.layers.0.1.weight",
    "ht_demucs/encoder_2/d_conv_2/sequential_4/group_normalization_8/beta": "encoder.1.dconv.layers.0.1.bias",
    "ht_demucs/encoder_2/d_conv_2/sequential_4/conv1d_12/kernel": "encoder.1.dconv.layers.0.3.weight",
    "ht_demucs/encoder_2/d_conv_2/sequential_4/conv1d_12/bias": "encoder.1.dconv.layers.0.3.bias",
    "ht_demucs/encoder_2/d_conv_2/sequential_4/group_normalization_9/gamma": "encoder.1.dconv.layers.0.4.weight",
    "ht_demucs/encoder_2/d_conv_2/sequential_4/group_normalization_9/beta": "encoder.1.dconv.layers.0.4.bias",
    "layer_scale_4/scale": "encoder.1.dconv.layers.0.6.scale",
    "ht_demucs/encoder_2/d_conv_2/sequential_5/conv1d_13/kernel": "encoder.1.dconv.layers.1.0.weight",
    "ht_demucs/encoder_2/d_conv_2/sequential_5/conv1d_13/bias": "encoder.1.dconv.layers.1.0.bias",
    "ht_demucs/encoder_2/d_conv_2/sequential_5/group_normalization_10/gamma": "encoder.1.dconv.layers.1.1.weight",
    "ht_demucs/encoder_2/d_conv_2/sequential_5/group_normalization_10/beta": "encoder.1.dconv.layers.1.1.bias",
    "ht_demucs/encoder_2/d_conv_2/sequential_5/conv1d_14/kernel": "encoder.1.dconv.layers.1.3.weight",
    "ht_demucs/encoder_2/d_conv_2/sequential_5/conv1d_14/bias": "encoder.1.dconv.layers.1.3.bias",
    "ht_demucs/encoder_2/d_conv_2/sequential_5/group_normalization_11/gamma": "encoder.1.dconv.layers.1.4.weight",
    "ht_demucs/encoder_2/d_conv_2/sequential_5/group_normalization_11/beta": "encoder.1.dconv.layers.1.4.bias",
    "layer_scale_5/scale": "encoder.1.dconv.layers.1.6.scale",
}

z_encoder_2 = {
    "ht_demucs/encoder_4/conv2d_6/kernel": "encoder.2.conv.weight",
    "ht_demucs/encoder_4/conv2d_6/bias": "encoder.2.conv.bias",
    "ht_demucs/encoder_4/conv2d_7/kernel": "encoder.2.rewrite.weight",
    "ht_demucs/encoder_4/conv2d_7/bias": "encoder.2.rewrite.bias",
    "ht_demucs/encoder_4/d_conv_4/sequential_8/conv1d_22/kernel": "encoder.2.dconv.layers.0.0.weight",
    "ht_demucs/encoder_4/d_conv_4/sequential_8/conv1d_22/bias": "encoder.2.dconv.layers.0.0.bias",
    "ht_demucs/encoder_4/d_conv_4/sequential_8/group_normalization_16/gamma": "encoder.2.dconv.layers.0.1.weight",
    "ht_demucs/encoder_4/d_conv_4/sequential_8/group_normalization_16/beta": "encoder.2.dconv.layers.0.1.bias",
    "ht_demucs/encoder_4/d_conv_4/sequential_8/conv1d_23/kernel": "encoder.2.dconv.layers.0.3.weight",
    "ht_demucs/encoder_4/d_conv_4/sequential_8/conv1d_23/bias": "encoder.2.dconv.layers.0.3.bias",
    "ht_demucs/encoder_4/d_conv_4/sequential_8/group_normalization_17/gamma": "encoder.2.dconv.layers.0.4.weight",
    "ht_demucs/encoder_4/d_conv_4/sequential_8/group_normalization_17/beta": "encoder.2.dconv.layers.0.4.bias",
    "layer_scale_8/scale": "encoder.2.dconv.layers.0.6.scale",
    "ht_demucs/encoder_4/d_conv_4/sequential_9/conv1d_24/kernel": "encoder.2.dconv.layers.1.0.weight",
    "ht_demucs/encoder_4/d_conv_4/sequential_9/conv1d_24/bias": "encoder.2.dconv.layers.1.0.bias",
    "ht_demucs/encoder_4/d_conv_4/sequential_9/group_normalization_18/gamma": "encoder.2.dconv.layers.1.1.weight",
    "ht_demucs/encoder_4/d_conv_4/sequential_9/group_normalization_18/beta": "encoder.2.dconv.layers.1.1.bias",
    "ht_demucs/encoder_4/d_conv_4/sequential_9/conv1d_25/kernel": "encoder.2.dconv.layers.1.3.weight",
    "ht_demucs/encoder_4/d_conv_4/sequential_9/conv1d_25/bias": "encoder.2.dconv.layers.1.3.bias",
    "ht_demucs/encoder_4/d_conv_4/sequential_9/group_normalization_19/gamma": "encoder.2.dconv.layers.1.4.weight",
    "ht_demucs/encoder_4/d_conv_4/sequential_9/group_normalization_19/beta": "encoder.2.dconv.layers.1.4.bias",
    "layer_scale_9/scale": "encoder.2.dconv.layers.1.6.scale",
}

z_encoder_3 = {
    "ht_demucs/encoder_6/conv2d_9/kernel": "encoder.3.conv.weight",
    "ht_demucs/encoder_6/conv2d_9/bias": "encoder.3.conv.bias",
    "ht_demucs/encoder_6/conv2d_10/kernel": "encoder.3.rewrite.weight",
    "ht_demucs/encoder_6/conv2d_10/bias": "encoder.3.rewrite.bias",
    "ht_demucs/encoder_6/d_conv_6/sequential_12/conv1d_33/kernel": "encoder.3.dconv.layers.0.0.weight",
    "ht_demucs/encoder_6/d_conv_6/sequential_12/conv1d_33/bias": "encoder.3.dconv.layers.0.0.bias",
    "ht_demucs/encoder_6/d_conv_6/sequential_12/group_normalization_24/gamma": "encoder.3.dconv.layers.0.1.weight",
    "ht_demucs/encoder_6/d_conv_6/sequential_12/group_normalization_24/beta": "encoder.3.dconv.layers.0.1.bias",
    "ht_demucs/encoder_6/d_conv_6/sequential_12/conv1d_34/kernel": "encoder.3.dconv.layers.0.3.weight",
    "ht_demucs/encoder_6/d_conv_6/sequential_12/conv1d_34/bias": "encoder.3.dconv.layers.0.3.bias",
    "ht_demucs/encoder_6/d_conv_6/sequential_12/group_normalization_25/gamma": "encoder.3.dconv.layers.0.4.weight",
    "ht_demucs/encoder_6/d_conv_6/sequential_12/group_normalization_25/beta": "encoder.3.dconv.layers.0.4.bias",
    "layer_scale_12/scale": "encoder.3.dconv.layers.0.6.scale",
    "ht_demucs/encoder_6/d_conv_6/sequential_13/conv1d_35/kernel": "encoder.3.dconv.layers.1.0.weight",
    "ht_demucs/encoder_6/d_conv_6/sequential_13/conv1d_35/bias": "encoder.3.dconv.layers.1.0.bias",
    "ht_demucs/encoder_6/d_conv_6/sequential_13/group_normalization_26/gamma": "encoder.3.dconv.layers.1.1.weight",
    "ht_demucs/encoder_6/d_conv_6/sequential_13/group_normalization_26/beta": "encoder.3.dconv.layers.1.1.bias",
    "ht_demucs/encoder_6/d_conv_6/sequential_13/conv1d_36/kernel": "encoder.3.dconv.layers.1.3.weight",
    "ht_demucs/encoder_6/d_conv_6/sequential_13/conv1d_36/bias": "encoder.3.dconv.layers.1.3.bias",
    "ht_demucs/encoder_6/d_conv_6/sequential_13/group_normalization_27/gamma": "encoder.3.dconv.layers.1.4.weight",
    "ht_demucs/encoder_6/d_conv_6/sequential_13/group_normalization_27/beta": "encoder.3.dconv.layers.1.4.bias",
    "layer_scale_13/scale": "encoder.3.dconv.layers.1.6.scale",
}

z_decoder_0 = {
    "ht_demucs/decoder_6/conv2d_transpose_3/kernel": "decoder.0.conv_tr.weight",
    "ht_demucs/decoder_6/conv2d_transpose_3/bias": "decoder.0.conv_tr.bias",
    "ht_demucs/decoder_6/conv2d_11/kernel": "decoder.0.rewrite.weight",
    "ht_demucs/decoder_6/conv2d_11/bias": "decoder.0.rewrite.bias",
}

z_decoder_1 = {
    "ht_demucs/decoder_4/conv2d_transpose_2/kernel": "decoder.1.conv_tr.weight",
    "ht_demucs/decoder_4/conv2d_transpose_2/bias": "decoder.1.conv_tr.bias",
    "ht_demucs/decoder_4/conv2d_8/kernel": "decoder.1.rewrite.weight",
    "ht_demucs/decoder_4/conv2d_8/bias": "decoder.1.rewrite.bias",
}

z_decoder_2 = {
    "ht_demucs/decoder_2/conv2d_transpose_1/kernel": "decoder.2.conv_tr.weight",
    "ht_demucs/decoder_2/conv2d_transpose_1/bias": "decoder.2.conv_tr.bias",
    "ht_demucs/decoder_2/conv2d_5/kernel": "decoder.2.rewrite.weight",
    "ht_demucs/decoder_2/conv2d_5/bias": "decoder.2.rewrite.bias",
}

z_decoder_3 = {
    "ht_demucs/decoder/conv2d_transpose/kernel": "decoder.3.conv_tr.weight",
    "ht_demucs/decoder/conv2d_transpose/bias": "decoder.3.conv_tr.bias",
    "ht_demucs/decoder/conv2d_2/kernel": "decoder.3.rewrite.weight",
    "ht_demucs/decoder/conv2d_2/bias": "decoder.3.rewrite.bias",
}

freq_embed = {
    "ht_demucs/scaled_embedding/embedding/embeddings": "freq_emb.embedding.weight"
}

transformer = {
    "ht_demucs/cross_domain_transformer_encoder/layer_normalization/gamma": "crosstransformer.norm_in.weight",
    "ht_demucs/cross_domain_transformer_encoder/layer_normalization/beta": "crosstransformer.norm_in.bias",
    "ht_demucs/cross_domain_transformer_encoder/layer_normalization_1/gamma": "crosstransformer.norm_in_t.weight",
    "ht_demucs/cross_domain_transformer_encoder/layer_normalization_1/beta": "crosstransformer.norm_in_t.bias",
}

z_transformer_0 = {
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/multi_head_attention_layer/dense_20/kernel": "crosstransformer.layers.0.self_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/multi_head_attention_layer/dense_20/bias": "crosstransformer.layers.0.self_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/multi_head_attention_layer/dense_21/kernel": "crosstransformer.layers.0.self_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/multi_head_attention_layer/dense_21/bias": "crosstransformer.layers.0.self_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/multi_head_attention_layer/dense_22/kernel": "crosstransformer.layers.0.self_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/multi_head_attention_layer/dense_22/bias": "crosstransformer.layers.0.self_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/multi_head_attention_layer/dense_23/kernel": "crosstransformer.layers.0.self_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/multi_head_attention_layer/dense_23/bias": "crosstransformer.layers.0.self_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/sequential_16/dense/kernel": "crosstransformer.layers.0.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/sequential_16/dense/bias": "crosstransformer.layers.0.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/sequential_16/dense_1/kernel": "crosstransformer.layers.0.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/sequential_16/dense_1/bias": "crosstransformer.layers.0.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/layer_normalization_2/gamma": "crosstransformer.layers.0.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/layer_normalization_2/beta": "crosstransformer.layers.0.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/layer_normalization_3/gamma": "crosstransformer.layers.0.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/layer_normalization_3/beta": "crosstransformer.layers.0.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/group_normalization_32/gamma": "crosstransformer.layers.0.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer/group_normalization_32/beta": "crosstransformer.layers.0.norm_out.bias",
    "layer_scale_16/scale": "crosstransformer.layers.0.gamma_1.scale",
    "layer_scale_17/scale": "crosstransformer.layers.0.gamma_2.scale",
}

t_transformer_0 = {
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/multi_head_attention_layer_1/dense_24/kernel": "crosstransformer.layers_t.0.self_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/multi_head_attention_layer_1/dense_24/bias": "crosstransformer.layers_t.0.self_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/multi_head_attention_layer_1/dense_25/kernel": "crosstransformer.layers_t.0.self_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/multi_head_attention_layer_1/dense_25/bias": "crosstransformer.layers_t.0.self_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/multi_head_attention_layer_1/dense_26/kernel": "crosstransformer.layers_t.0.self_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/multi_head_attention_layer_1/dense_26/bias": "crosstransformer.layers_t.0.self_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/multi_head_attention_layer_1/dense_27/kernel": "crosstransformer.layers_t.0.self_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/multi_head_attention_layer_1/dense_27/bias": "crosstransformer.layers_t.0.self_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/sequential_17/dense_2/kernel": "crosstransformer.layers_t.0.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/sequential_17/dense_2/bias": "crosstransformer.layers_t.0.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/sequential_17/dense_3/kernel": "crosstransformer.layers_t.0.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/sequential_17/dense_3/bias": "crosstransformer.layers_t.0.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/layer_normalization_4/gamma": "crosstransformer.layers_t.0.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/layer_normalization_4/beta": "crosstransformer.layers_t.0.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/layer_normalization_5/gamma": "crosstransformer.layers_t.0.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/layer_normalization_5/beta": "crosstransformer.layers_t.0.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/group_normalization_33/gamma": "crosstransformer.layers_t.0.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_1/group_normalization_33/beta": "crosstransformer.layers_t.0.norm_out.bias",
    "layer_scale_18/scale": "crosstransformer.layers_t.0.gamma_1.scale",
    "layer_scale_19/scale": "crosstransformer.layers_t.0.gamma_2.scale",
}

z_transformer_1 = {
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/multi_head_attention_layer_2/dense_28/kernel": "crosstransformer.layers.1.cross_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/multi_head_attention_layer_2/dense_28/bias": "crosstransformer.layers.1.cross_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/multi_head_attention_layer_2/dense_29/kernel": "crosstransformer.layers.1.cross_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/multi_head_attention_layer_2/dense_29/bias": "crosstransformer.layers.1.cross_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/multi_head_attention_layer_2/dense_30/kernel": "crosstransformer.layers.1.cross_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/multi_head_attention_layer_2/dense_30/bias": "crosstransformer.layers.1.cross_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/multi_head_attention_layer_2/dense_31/kernel": "crosstransformer.layers.1.cross_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/multi_head_attention_layer_2/dense_31/bias": "crosstransformer.layers.1.cross_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/dense_4/kernel": "crosstransformer.layers.1.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/dense_4/bias": "crosstransformer.layers.1.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/dense_5/kernel": "crosstransformer.layers.1.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/dense_5/bias": "crosstransformer.layers.1.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/layer_normalization_6/gamma": "crosstransformer.layers.1.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/layer_normalization_6/beta": "crosstransformer.layers.1.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/layer_normalization_7/gamma": "crosstransformer.layers.1.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/layer_normalization_7/beta": "crosstransformer.layers.1.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/layer_normalization_8/gamma": "crosstransformer.layers.1.norm3.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/layer_normalization_8/beta": "crosstransformer.layers.1.norm3.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/group_normalization_34/gamma": "crosstransformer.layers.1.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer/group_normalization_34/beta": "crosstransformer.layers.1.norm_out.bias",
    "layer_scale_20/scale": "crosstransformer.layers.1.gamma_1.scale",
    "layer_scale_21/scale": "crosstransformer.layers.1.gamma_2.scale",
}

t_transformer_1 = {
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/multi_head_attention_layer_3/dense_32/kernel": "crosstransformer.layers_t.1.cross_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/multi_head_attention_layer_3/dense_32/bias": "crosstransformer.layers_t.1.cross_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/multi_head_attention_layer_3/dense_33/kernel": "crosstransformer.layers_t.1.cross_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/multi_head_attention_layer_3/dense_33/bias": "crosstransformer.layers_t.1.cross_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/multi_head_attention_layer_3/dense_34/kernel": "crosstransformer.layers_t.1.cross_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/multi_head_attention_layer_3/dense_34/bias": "crosstransformer.layers_t.1.cross_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/multi_head_attention_layer_3/dense_35/kernel": "crosstransformer.layers_t.1.cross_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/multi_head_attention_layer_3/dense_35/bias": "crosstransformer.layers_t.1.cross_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/dense_6/kernel": "crosstransformer.layers_t.1.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/dense_6/bias": "crosstransformer.layers_t.1.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/dense_7/kernel": "crosstransformer.layers_t.1.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/dense_7/bias": "crosstransformer.layers_t.1.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/layer_normalization_9/gamma": "crosstransformer.layers_t.1.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/layer_normalization_9/beta": "crosstransformer.layers_t.1.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/layer_normalization_10/gamma": "crosstransformer.layers_t.1.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/layer_normalization_10/beta": "crosstransformer.layers_t.1.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/layer_normalization_11/gamma": "crosstransformer.layers_t.1.norm3.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/layer_normalization_11/beta": "crosstransformer.layers_t.1.norm3.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/group_normalization_35/gamma": "crosstransformer.layers_t.1.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_1/group_normalization_35/beta": "crosstransformer.layers_t.1.norm_out.bias",
    "layer_scale_22/scale": "crosstransformer.layers_t.1.gamma_1.scale",
    "layer_scale_23/scale": "crosstransformer.layers_t.1.gamma_2.scale",
}

z_transformer_2 = {
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/multi_head_attention_layer_4/dense_36/kernel": "crosstransformer.layers.2.self_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/multi_head_attention_layer_4/dense_36/bias": "crosstransformer.layers.2.self_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/multi_head_attention_layer_4/dense_37/kernel": "crosstransformer.layers.2.self_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/multi_head_attention_layer_4/dense_37/bias": "crosstransformer.layers.2.self_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/multi_head_attention_layer_4/dense_38/kernel": "crosstransformer.layers.2.self_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/multi_head_attention_layer_4/dense_38/bias": "crosstransformer.layers.2.self_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/multi_head_attention_layer_4/dense_39/kernel": "crosstransformer.layers.2.self_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/multi_head_attention_layer_4/dense_39/bias": "crosstransformer.layers.2.self_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/sequential_18/dense_8/kernel": "crosstransformer.layers.2.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/sequential_18/dense_8/bias": "crosstransformer.layers.2.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/sequential_18/dense_9/kernel": "crosstransformer.layers.2.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/sequential_18/dense_9/bias": "crosstransformer.layers.2.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/layer_normalization_12/gamma": "crosstransformer.layers.2.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/layer_normalization_12/beta": "crosstransformer.layers.2.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/layer_normalization_13/gamma": "crosstransformer.layers.2.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/layer_normalization_13/beta": "crosstransformer.layers.2.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/group_normalization_36/gamma": "crosstransformer.layers.2.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_2/group_normalization_36/beta": "crosstransformer.layers.2.norm_out.bias",
    "layer_scale_24/scale": "crosstransformer.layers.2.gamma_1.scale",
    "layer_scale_25/scale": "crosstransformer.layers.2.gamma_2.scale",
}

t_transformer_2 = {
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/multi_head_attention_layer_5/dense_40/kernel": "crosstransformer.layers_t.2.self_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/multi_head_attention_layer_5/dense_40/bias": "crosstransformer.layers_t.2.self_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/multi_head_attention_layer_5/dense_41/kernel": "crosstransformer.layers_t.2.self_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/multi_head_attention_layer_5/dense_41/bias": "crosstransformer.layers_t.2.self_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/multi_head_attention_layer_5/dense_42/kernel": "crosstransformer.layers_t.2.self_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/multi_head_attention_layer_5/dense_42/bias": "crosstransformer.layers_t.2.self_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/multi_head_attention_layer_5/dense_43/kernel": "crosstransformer.layers_t.2.self_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/multi_head_attention_layer_5/dense_43/bias": "crosstransformer.layers_t.2.self_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/sequential_19/dense_10/kernel": "crosstransformer.layers_t.2.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/sequential_19/dense_10/bias": "crosstransformer.layers_t.2.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/sequential_19/dense_11/kernel": "crosstransformer.layers_t.2.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/sequential_19/dense_11/bias": "crosstransformer.layers_t.2.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/layer_normalization_14/gamma": "crosstransformer.layers_t.2.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/layer_normalization_14/beta": "crosstransformer.layers_t.2.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/layer_normalization_15/gamma": "crosstransformer.layers_t.2.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/layer_normalization_15/beta": "crosstransformer.layers_t.2.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/group_normalization_37/gamma": "crosstransformer.layers_t.2.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_3/group_normalization_37/beta": "crosstransformer.layers_t.2.norm_out.bias",
    "layer_scale_26/scale": "crosstransformer.layers_t.2.gamma_1.scale",
    "layer_scale_27/scale": "crosstransformer.layers_t.2.gamma_2.scale",
}

z_transformer_3 = {
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/multi_head_attention_layer_6/dense_44/kernel": "crosstransformer.layers.3.cross_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/multi_head_attention_layer_6/dense_44/bias": "crosstransformer.layers.3.cross_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/multi_head_attention_layer_6/dense_45/kernel": "crosstransformer.layers.3.cross_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/multi_head_attention_layer_6/dense_45/bias": "crosstransformer.layers.3.cross_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/multi_head_attention_layer_6/dense_46/kernel": "crosstransformer.layers.3.cross_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/multi_head_attention_layer_6/dense_46/bias": "crosstransformer.layers.3.cross_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/multi_head_attention_layer_6/dense_47/kernel": "crosstransformer.layers.3.cross_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/multi_head_attention_layer_6/dense_47/bias": "crosstransformer.layers.3.cross_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/dense_12/kernel": "crosstransformer.layers.3.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/dense_12/bias": "crosstransformer.layers.3.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/dense_13/kernel": "crosstransformer.layers.3.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/dense_13/bias": "crosstransformer.layers.3.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/layer_normalization_16/gamma": "crosstransformer.layers.3.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/layer_normalization_16/beta": "crosstransformer.layers.3.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/layer_normalization_17/gamma": "crosstransformer.layers.3.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/layer_normalization_17/beta": "crosstransformer.layers.3.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/layer_normalization_18/gamma": "crosstransformer.layers.3.norm3.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/layer_normalization_18/beta": "crosstransformer.layers.3.norm3.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/group_normalization_38/gamma": "crosstransformer.layers.3.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_2/group_normalization_38/beta": "crosstransformer.layers.3.norm_out.bias",
    "layer_scale_28/scale": "crosstransformer.layers.3.gamma_1.scale",
    "layer_scale_29/scale": "crosstransformer.layers.3.gamma_2.scale",
}

t_transformer_3 = {
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/multi_head_attention_layer_7/dense_48/kernel": "crosstransformer.layers_t.3.cross_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/multi_head_attention_layer_7/dense_48/bias": "crosstransformer.layers_t.3.cross_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/multi_head_attention_layer_7/dense_49/kernel": "crosstransformer.layers_t.3.cross_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/multi_head_attention_layer_7/dense_49/bias": "crosstransformer.layers_t.3.cross_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/multi_head_attention_layer_7/dense_50/kernel": "crosstransformer.layers_t.3.cross_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/multi_head_attention_layer_7/dense_50/bias": "crosstransformer.layers_t.3.cross_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/multi_head_attention_layer_7/dense_51/kernel": "crosstransformer.layers_t.3.cross_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/multi_head_attention_layer_7/dense_51/bias": "crosstransformer.layers_t.3.cross_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/dense_14/kernel": "crosstransformer.layers_t.3.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/dense_14/bias": "crosstransformer.layers_t.3.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/dense_15/kernel": "crosstransformer.layers_t.3.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/dense_15/bias": "crosstransformer.layers_t.3.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/layer_normalization_19/gamma": "crosstransformer.layers_t.3.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/layer_normalization_19/beta": "crosstransformer.layers_t.3.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/layer_normalization_20/gamma": "crosstransformer.layers_t.3.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/layer_normalization_20/beta": "crosstransformer.layers_t.3.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/layer_normalization_21/gamma": "crosstransformer.layers_t.3.norm3.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/layer_normalization_21/beta": "crosstransformer.layers_t.3.norm3.bias",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/group_normalization_39/gamma": "crosstransformer.layers_t.3.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/cross_attention_encoder_layer_3/group_normalization_39/beta": "crosstransformer.layers_t.3.norm_out.bias",
    "layer_scale_30/scale": "crosstransformer.layers_t.3.gamma_1.scale",
    "layer_scale_31/scale": "crosstransformer.layers_t.3.gamma_2.scale",
}

z_transformer_4 = {
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/multi_head_attention_layer_8/dense_52/kernel": "crosstransformer.layers.4.self_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/multi_head_attention_layer_8/dense_52/bias": "crosstransformer.layers.4.self_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/multi_head_attention_layer_8/dense_53/kernel": "crosstransformer.layers.4.self_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/multi_head_attention_layer_8/dense_53/bias": "crosstransformer.layers.4.self_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/multi_head_attention_layer_8/dense_54/kernel": "crosstransformer.layers.4.self_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/multi_head_attention_layer_8/dense_54/bias": "crosstransformer.layers.4.self_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/multi_head_attention_layer_8/dense_55/kernel": "crosstransformer.layers.4.self_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/multi_head_attention_layer_8/dense_55/bias": "crosstransformer.layers.4.self_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/sequential_20/dense_16/kernel": "crosstransformer.layers.4.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/sequential_20/dense_16/bias": "crosstransformer.layers.4.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/sequential_20/dense_17/kernel": "crosstransformer.layers.4.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/sequential_20/dense_17/bias": "crosstransformer.layers.4.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/layer_normalization_22/gamma": "crosstransformer.layers.4.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/layer_normalization_22/beta": "crosstransformer.layers.4.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/layer_normalization_23/gamma": "crosstransformer.layers.4.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/layer_normalization_23/beta": "crosstransformer.layers.4.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/group_normalization_40/gamma": "crosstransformer.layers.4.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_4/group_normalization_40/beta": "crosstransformer.layers.4.norm_out.bias",
    "layer_scale_32/scale": "crosstransformer.layers.4.gamma_1.scale",
    "layer_scale_33/scale": "crosstransformer.layers.4.gamma_2.scale",
}

t_transformer_4 = {
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/multi_head_attention_layer_9/dense_56/kernel": "crosstransformer.layers_t.4.self_attn.query.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/multi_head_attention_layer_9/dense_56/bias": "crosstransformer.layers_t.4.self_attn.query.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/multi_head_attention_layer_9/dense_57/kernel": "crosstransformer.layers_t.4.self_attn.key.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/multi_head_attention_layer_9/dense_57/bias": "crosstransformer.layers_t.4.self_attn.key.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/multi_head_attention_layer_9/dense_58/kernel": "crosstransformer.layers_t.4.self_attn.value.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/multi_head_attention_layer_9/dense_58/bias": "crosstransformer.layers_t.4.self_attn.value.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/multi_head_attention_layer_9/dense_59/kernel": "crosstransformer.layers_t.4.self_attn.out_proj.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/multi_head_attention_layer_9/dense_59/bias": "crosstransformer.layers_t.4.self_attn.out_proj.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/sequential_21/dense_18/kernel": "crosstransformer.layers_t.4.linear1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/sequential_21/dense_18/bias": "crosstransformer.layers_t.4.linear1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/sequential_21/dense_19/kernel": "crosstransformer.layers_t.4.linear2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/sequential_21/dense_19/bias": "crosstransformer.layers_t.4.linear2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/layer_normalization_24/gamma": "crosstransformer.layers_t.4.norm1.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/layer_normalization_24/beta": "crosstransformer.layers_t.4.norm1.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/layer_normalization_25/gamma": "crosstransformer.layers_t.4.norm2.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/layer_normalization_25/beta": "crosstransformer.layers_t.4.norm2.bias",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/group_normalization_41/gamma": "crosstransformer.layers_t.4.norm_out.weight",
    "ht_demucs/cross_domain_transformer_encoder/transformer_encoder_layer_5/group_normalization_41/beta": "crosstransformer.layers_t.4.norm_out.bias",
    "layer_scale_34/scale": "crosstransformer.layers_t.4.gamma_1.scale",
    "layer_scale_35/scale": "crosstransformer.layers_t.4.gamma_2.scale",
}

mapping = {
    **freq_embed,
    **t_encoder_0,
    **t_encoder_1,
    **t_encoder_2,
    **t_encoder_3,
    **t_decoder_0,
    **t_decoder_1,
    **t_decoder_2,
    **t_decoder_3,
    **z_encoder_0,
    **z_encoder_1,
    **z_encoder_2,
    **z_encoder_3,
    **z_decoder_0,
    **z_decoder_1,
    **z_decoder_2,
    **z_decoder_3,
    **transformer,
    **t_transformer_0,
    **t_transformer_1,
    **t_transformer_2,
    **t_transformer_3,
    **t_transformer_4,
    **z_transformer_0,
    **z_transformer_1,
    **z_transformer_2,
    **z_transformer_3,
    **z_transformer_4,
}
